#!/usr/bin/env bash

list_unicodemoji() {
  if [ -z "$XDG_CACHE_DIR" ]
  then
    cache_base="$HOME/.cache"
  else
    cache_base="$XDG_CACHE_DIR"
  fi

  unicodemoji_cache="$cache_base/unicodemoji/"
  gitmoji_out="$unicodemoji_cache/gitmojis.json"
  emoji_out="$unicodemoji_cache/emojis.json"

  mkdir -p "$unicodemoji_cache"

  [ -e "$gitmoji_out"  ] || wget -q https://raw.githubusercontent.com/carloscuesta/gitmoji/master/src/data/gitmojis.json -O "$gitmoji_out"
  [ -e "$emoji_out"  ] || wget -q https://gist.githubusercontent.com/oliveratgithub/0bf11a9aff0d6da7b46f1490f86a71eb/raw/d8e4b78cfe66862cf3809443c1dba017f37b61db/emojis.json -O "$emoji_out"

  jq -r '.emojis[] | .emoji + " " + .name + " " + .category' "$emoji_out"
  jq -r '.gitmojis[] | .emoji + " " + .description + " " + .name' "$gitmoji_out"
}

if [ $# -eq 0 ]
then
  list_unicodemoji | fzf | egrep -o '^.'
else
  list_unicodemoji
fi
